version: 2
jobs:
  build:
    docker:
#      - image: hashicorp/packer
      - image: alpine
#    working_directory: ~/packer
    steps:
#      - checkout
      - run:
          command: |
            apk add curl
            curl -H 'Accept: application/vnd.github.v3.raw' -o test.txt \
                 -L https://api.github.com/repos/megurrola/test/contents/dir/file.txt\?access_token=$GITHUB_TOKEN\&ref=$CIRCLE_BRANCH
            ls -l test.txt;

#         name: Build image
#          command: packer build packer/jet8-code-nginx-phpfpm.json
