version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Build image
          command: packer build packer/code-nginx-phpfpm.json
