version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Build image
          command: packer build packer/jet8-code-nginx-phpfpm.json
  deploy:
    docker:
      - image: circleci/awscli:latest
    steps:
      - run:
          name: Update AWS launch template
          commanmd: aws --version
