version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer
    working_directory: ~/packer
    steps:
#      - checkout
      - run:
          command: |
             apk add curl
             curl -v -H 'Accept: application/vnd.github.v3.raw' -o pepe/test.txt \
                  https://api.github.com/repos/megurrola/test/contents/test/test.txt\?access_token=$GITHUB_TOKEN&ref=$CIRCLE_BRANCH
             ls -l pepe/
             mount
#          name: Build image
#          command: packer build packer/jet8-code-nginx-phpfpm.json
