version: 2
jobs:
  build:
    docker:
#      - image: hashicorp/packer
      - image: alpine
#    working_directory: ~/packer
    steps:
#      - checkout
      - run:
          command: |
             wget -O test.txt --header='Accept: application/vnd.github.v3.raw' \
                  https://api.github.com/repos/megurrola/test/contents/dir/file.txt?ref=$CIRCLE_BRANCH&access_token=$GITHUB_TOKEN;
             echo $GITHUB_TOKEN;
             echo $CIRCLE_BRANCH; 
             ls -l;


#         name: Build image
#          command: packer build packer/jet8-code-nginx-phpfpm.json
