version: 2
jobs:
  build:
    docker:
#      - image: hashicorp/packer
      - image: alpine
#    working_directory: ~/packer
    steps:
#      - checkout
      - run:
          command: |
             wget -O /tmp/test.txt --header='Accept: application/vnd.github.v3.raw' \
                  https://api.github.com/repos/megurrola/test/contents/dir/file.txt?ref=$CIRCLE_BRANCH&access_token=$GITHUB_TOKEN 

      - store_artifacts:
          path: /tmp/test.txt
          destination: artifact-file

#         name: Build image
#          command: packer build packer/jet8-code-nginx-phpfpm.json
