---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:

# Copy the script needed to disable the already running instances in the ASG
   - name: Copy user_data script
     copy:
        src: files/user_data/check_instances_amiid.sh
        dest: /var/lib/cloud/instance/user-data.txt
        mode: 0755
